apiVersion: apps/v1
kind: Deployment
metadata:
  name: actividad-deployment
  labels:
    app: actividadintegradora
spec:
  replicas: 3
  selector:
    matchLabels:
      app: actividadintegradora
  template:
    metadata:
      labels:
        app: actividadintegradora
    spec:
      containers:
      - name: django
        image: gcr.io/$PROJECT_ID/actividadintegradora
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "ActividadIntegradora.settings"
