apiVersion: v1
kind: Service
metadata:
  name: actividad-service
spec:
  selector:
    app: actividadintegradora
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
